on:
  pull_request:
    types: closed

jobs:
  specific_review_requested:
    runs-on: ubuntu-latest
    steps:
    - name: install-databricks-cli
      uses: microsoft/install-databricks-cli@v1.0.0
    - shell: bash
      run: |
        expr 1 + 1 > output.log
